name: "WODaboard"
on:
  push:
    branches:
      - main
      
jobs:
  wod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: |
          curl \
          -X POST \
          -H "x-vestaboard-api-key: $VB_SUB_KEY" \
          -H "x-vestaboard-api-secret: $VB_SUB_SECRET" \
          -d '{"text": "{64}New Wodaboard Deployment{64}"}' \
          https://subscriptions.vestaboard.com/subscriptions/$VB_SUB_ID/message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VB_SUB_ID: ${{ secrets.VB_SUB_ID }}
          VB_SUB_KEY: ${{ secrets.VB_SUB_KEY }}
          VB_SUB_SECRET: ${{ secrets.VB_SUB_SECRET }}